backend:   
  name: git-gateway   
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
- name: "news" # Used in routes, e.g., /admin/collections/news
  label: "News" # Used in the UI
  folder: "content/news" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - label: "Title"
      name: "title"
      widget: "string"
    - label: "Body",
      name: "body", 
      widget: "markdown"
    - label: "Publish Date"
      name: "date"
      required: true
      widget: "datetime"
    - label: "Author"
      name: "author"
      required: false
      widget: "string"
    - label: "Image"
      name: "image"
      required: false
      widget: "image"
    - label: "Draft"
      name: "draft"
      required: false
      widget: "boolean"
      default: true
    - label: "Categories"
      name: "categories"
      required: false
      widget: "list"
    - label: "Tags"
      name: "tags"
      required: false
      widget: "list"
